use ETRADE

--SELECT
SELECT * FROM CUSTOMERS

--EKLEME
INSERT INTO CUSTOMERS
(CUSTOMERNAME,CITY,BIRTHDATE,DISTRICT,GENDER)
VALUES
('MEHMET ÖZAL', 'ANTALYA', '1990-12-21', 'ALANYA', 'E')

--GÜNCELLEME
UPDATE CUSTOMERS SET NATION = 'TR'
UPDATE CUSTOMERS SET AGE = DATEDIFF(YEAR,BIRTHDATE,GETDATE())

